config/routes.rb
Rails.application.routes.draw do
  resources :suggestions, only: [:index]

  post 'suggestions/suggest-snacks' => 'suggestions#suggest_snack'
  post 'suggestions/up' => 'suggestions#upvote'
  post 'suggestions/down' => 'suggestions#downvote'

  resources :snacks
  resources :voting, only: [:index]
  resources :employees

  root 'suggestions#index'
end

app/models/snack.rb
class Snack
  require 'net/http'
  require 'json'
 
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongo::Voteable
  include ActiveModel::Validations

  field :name, type: String
  field :optional, type: Mongoid::Boolean
  field :purchased_locations, type: String
  field :purchased_count, type: Integer
  field :last_purchased_date, type: String
  field :uid, type: Integer

  scope :current_purchases, lambda{where(optional: false)}
  scope :not_purchased, lambda{where(purchased_count: 0)}

  validates_presence_of :purchased_locations

  # set points for each vote
  voteable self, :up => +1, :down => -1

  # Checks to see if record exists before
  # inserting into the database
  def self.ignore_duplicates(suid)
  	return true if(self.find_by(uid: suid).present?)
  	rescue Mongoid::Errors::DocumentNotFound  => e
  	return false
  end

  # Fetches json data and stores it as
  # a collection in DB. Avoids calling
  # api during each request
  def self.update_snacks
	url = 'https://api-snacks.nerderylabs.com/v1/snacks/?ApiKey=376b38aa-a42b-49dd-8ff6-0ffababe8b79'
	uri = URI(url)
	response = Net::HTTP.get(uri)

	sample_data = JSON.parse(response)

 	(0..sample_data.size-1).each do |snk|

 		if( !(ignore_duplicates(sample_data[snk]["id"]) ) )

	 		snack_obj = self.new
	 		snack_obj.name = sample_data[snk]["name"]
	 		snack_obj.optional = sample_data[snk]["optional"]
	 		snack_obj.purchased_locations = sample_data[snk]["purchaseLocations"] 
	 		snack_obj.purchased_count = sample_data[snk]["purchaseCount"]
	 		snack_obj.last_purchased_date = sample_data[snk]["lastPurchaseDate"]
	 		snack_obj.uid = sample_data[snk]["id"]

			snack_obj.save!
		end

		puts "record exists"

	end
  end 

end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  before_action :set_snack, only: [:show, :edit, :update, :destroy]

  # GET /snacks
  # GET /snacks.json
  def index
    @snacks = Snack.all
  end

  # GET /snacks/1
  # GET /snacks/1.json
  def show
  end

  # GET /snacks/new
  def new
    # @snack = Snack.new
    Snack.update_snacks
    redirect_to snacks_path
  end

  # GET /snacks/1/edit
  def edit
  end

  # POST /snacks
  # POST /snacks.json
  def create
    @snack = Snack.new(snack_params)

    respond_to do |format|
      if @snack.save
        format.html { redirect_to @snack, notice: 'Snack was successfully created.' }
        format.json { render :show, status: :created, location: @snack }
      else
        format.html { render :new }
        format.json { render json: @snack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snacks/1
  # PATCH/PUT /snacks/1.json
  def update
    respond_to do |format|
      if @snack.update(snack_params)
        format.html { redirect_to @snack, notice: 'Snack was successfully updated.' }
        format.json { render :show, status: :ok, location: @snack }
      else
        format.html { render :edit }
        format.json { render json: @snack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snacks/1
  # DELETE /snacks/1.json
  def destroy
    @snack.destroy
    respond_to do |format|
      format.html { redirect_to snacks_url, notice: 'Snack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snack
      @snack = Snack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snack_params
      params.require(:snack).permit(:name, :optional, :purchased_locations, :purchased_count, :last_purchased_date, :uid)
    end
end

app/helpers/snacks_helper.rb
module SnacksHelper
end

app/views/snacks/_form.html.erb
<%= form_for(@snack) do |f| %>
  <% if @snack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snack.errors.count, "error") %> prohibited this snack from being saved:</h2>

      <ul>
      <% @snack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :optional %><br>
    <%= f.check_box :optional %>
  </div>
  <div class="field">
    <%= f.label :purchased_locations %><br>
    <%= f.text_field :purchased_locations %>
  </div>
  <div class="field">
    <%= f.label :purchased_count %><br>
    <%= f.number_field :purchased_count %>
  </div>
  <div class="field">
    <%= f.label :last_purchased_date %><br>
    <%= f.text_field :last_purchased_date %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.number_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snacks/edit.html.erb
<h1>Editing Snack</h1>

<%= render 'form' %>

<%= link_to 'Show', @snack %> |
<%= link_to 'Back', snacks_path %>

app/views/snacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Snacks</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Optional</th>
      <th>Purchased locations</th>
      <th>Purchased count</th>
      <th>Last purchased date</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snacks.each do |snack| %>
      <tr>
        <td><%= snack.name %></td>
        <td><%= snack.optional %></td>
        <td><%= snack.purchased_locations %></td>
        <td><%= snack.purchased_count %></td>
        <td><%= snack.last_purchased_date %></td>
        <td><%= snack.uid %></td>
        <td><%= link_to 'Show', snack %></td>
        <td><%= link_to 'Edit', edit_snack_path(snack) %></td>
        <td><%= link_to 'Destroy', snack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Refresh Snacks', new_snack_path, class: "btn btn-success" %>

app/views/snacks/new.html.erb
<h1>New Snack</h1>

<%= render 'form' %>

<%= link_to 'Back', snacks_path %>

app/views/snacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @snack.name %>
</p>

<p>
  <strong>Optional:</strong>
  <%= @snack.optional %>
</p>

<p>
  <strong>Purchased locations:</strong>
  <%= @snack.purchased_locations %>
</p>

<p>
  <strong>Purchased count:</strong>
  <%= @snack.purchased_count %>
</p>

<p>
  <strong>Last purchased date:</strong>
  <%= @snack.last_purchased_date %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @snack.uid %>
</p>

<%= link_to 'Edit', edit_snack_path(@snack) %> |
<%= link_to 'Back', snacks_path %>