config/routes.rb
Rails.application.routes.draw do
  resources :suggestions, only: [:index]

  post 'suggestions/suggest-snacks' => 'suggestions#suggest_snack'
  post 'suggestions/up' => 'suggestions#upvote'
  post 'suggestions/down' => 'suggestions#downvote'

  resources :snacks
  resources :voting, only: [:index]
  resources :employees

  root 'suggestions#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nerdery Snack Food Ordering System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "NAT", root_path, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to "Voting", voting_index_path %>
                    </li>
                    <li>
                        <%= link_to "Suggestions", suggestions_path %>
                    </li>
                </ul>
				<ul class="nav navbar-nav navbar-right">
					<% if(current_user.present?) %>
						<li><a href="#"><%= current_user.first_name %> (<%= (3 - current_user.emp_vote_count.to_i) %> votes remaining for <%= Date.today.strftime("%B")%>)</a></li>
					<% else %>
						<li><%= link_to "create an account", new_employee_path %></li>
					<% end %>
				  
				</ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<div style="margin-bottom: 75px"></div>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% if flash[:error] %>
  <div class="error"><%= flash[:error] %></div>
<% end %>

<div class="common-error"> &nbsp; </div>

<div class="container">
	<div class="row">
		<%= yield %>
	</div>
</div>

</body>
</html>